name: "make"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  
jobs:
  docker-build:
    name: "docker-build"
    runs-on: "ubuntu-22.04"
    permissions:
      contents: "read"
      packages: "write"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "docker/setup-qemu-action@v2"
      - uses: "docker/setup-buildx-action@v2"
      - uses: "docker/login-action@v2"
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: "make docker-build"
        env:
          DOCKER_BUILD_FLAGS: "--push"
  probod:
    name: "bin/probod"
    runs-on: "ubuntu-22.04"
    permissions:
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-go@v5"
      - run: "make bin/probod"
  console:
    name: "@probo/console"
    runs-on: "ubuntu-22.04"
    permissions:
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-node@v4"
        with:
          node-version: 22
      - run: "npm ci"
      - run: "npm run lint"
      - run: "make @probo/console"
  fmt-check:
    name: "fmt-check"
    runs-on: "ubuntu-22.04"
    permissions:
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-node@v4"
      - run: "make fmt-check"
